pipeline {
  agent any

  environment {
    ANSIBLE_HOST_KEY_CHECKING = 'False'
  }

  stages {
    stage('Checkout Code') {
      steps {
        git url: 'https://github.com/nenavathsrinu/srinu-website.git', branch: 'main'
      }
    }

    stage('Run Ansible Playbook') {
      steps {
        dir('ansible') {
          sh '''
            echo "🔍 Running Ansible Playbook..."
            ansible-playbook -i inventory.ini playbook.yml
          '''
        }
      }
    }
  }

  post {
    success {
      echo '✅ Ansible playbook executed successfully.'
    }
    failure {
      echo '❌ Ansible execution failed. Please check the logs.'
    }
  }
}
